"""Formal mechanism-validation utilities for the CT->PET project."""

from .common import (
    BOOTSTRAP_REPLICATES,
    CALIBRATION_FRACTION,
    PARTITION_SEED,
    decision_guardrails,
    load_json,
    paired_patient_bootstrap,
    patient_partition,
    read_manifest,
    sign_flip_p,
    write_json,
    write_mechanism_manifest,
)
from .magnification import (
    CropBox,
    MagnificationView,
    PatientBootstrapResult,
    backproject_crop,
    bootstrap_patient_balanced_slope,
    couple_noise_to_crop,
    crop_resize,
    lesion_crop_box,
    patient_balanced_slope,
)
from .magnification_audit import (
    AuditTables,
    CohortArrays,
    build_primary_gate,
    compute_gate_statistics,
    run_frozen_magnification_audit,
    validate_cohort,
    write_audit_artifacts,
)

__all__ = [
    "BOOTSTRAP_REPLICATES",
    "CALIBRATION_FRACTION",
    "PARTITION_SEED",
    "decision_guardrails",
    "load_json",
    "paired_patient_bootstrap",
    "patient_partition",
    "read_manifest",
    "sign_flip_p",
    "write_json",
    "write_mechanism_manifest",
    "AuditTables",
    "CohortArrays",
    "CropBox",
    "MagnificationView",
    "PatientBootstrapResult",
    "backproject_crop",
    "bootstrap_patient_balanced_slope",
    "build_primary_gate",
    "compute_gate_statistics",
    "couple_noise_to_crop",
    "crop_resize",
    "lesion_crop_box",
    "patient_balanced_slope",
    "run_frozen_magnification_audit",
    "validate_cohort",
    "write_audit_artifacts",
]
